filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
#      - /var/app/log/*.log
    stream: "all"
    ids: "*"


filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true
- module: auditd
  log:
    enabled: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["log"]
      target: "json"
      overwrite_keys: true

setup.dashboards.enabled: true
setup.kibana.host: "192.168.0.13:5601"

#output.logstash:
#  hosts: ["192.168.0.13:5046"]

output.console:
  enabled: true

logging.json: true
logging.metrics.enabled: true

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["192.168.0.13:9200"]